### ISSUE TITLE
How to get current language that has been set?

### ISSUE THREAD

**Issue by Zorig** [serdimoa/gatsby-plugin-react-i18next-v10#3]
How to get current language when using createPage in gatsby-node? @serdimoa

**Comment by serdimoa** [comment]
> How to get current language when using createPage in gatsby-node? @serdimoa

Every page have [context](https://github.com/hupe1980/gatsby-i18n/blob/57e267814013cb3680cd32f09f2696abc70782e8/packages/gatsby-i18n/src/plugin/onCreatePage.js#L37) on create page.
